meroherb/chatting/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'chatting'

urlpatterns=[
    path('',views.inbox, name='inbox' ),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

meroherb/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static

app_name='core'

urlpatterns=[
    path('signup/',views.signup,name='signup'),
    path('login/',LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),name="login"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'), name="password_reset"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_sent.html'), name="password_reset_done"), 
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_form.html'), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_done.html'), name="password_reset_complete"), 

    path('main/',views.mainpage,name="main"),


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

meroherb/dashboard/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView

from . import views
from core import urls
from userprofile import urls

app_name='dashboard'

urlpatterns=[
    path('',include('core.urls')),
    path('dashboard/',views.dashboardView,name='dashboard'),
    path('products/',include('item.urls')),
    path('logout/', views.logout_view, name='logout'),
    path('profile/<int:pk>',views.sellerprofile,name="sellerprofile"),
    path('home/',views.home,name="home"),
    path('', include('userprofile.urls')),
]

meroherb/item/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from .views import GeneratePDF

app_name = 'item'
urlpatterns =[
    path('new/', views.new, name='new'),
    path('browse/',views.browse,name='browse'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('category/<str:pro>',views.Category_view,name="category_view"),
    path('buy_item/<int:pk>/', views.buy_item, name='buy_item'),
    path('generate_pdf/<int:bill_no>/', GeneratePDF.as_view(), name='generate_pdf'),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

meroherb/meroherb/urls.py
# main/urls.py

from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from core.views import mainpage
from django.urls import path, include

# Import Debug Toolbar only for development


app_name = "meroherb"

urlpatterns = [
    path('', include('core.urls')),
    path('',mainpage,name="first"),
    path('', include('dashboard.urls')),
    path('password_reset/', include('django.contrib.auth.urls')),
    path('', include('item.urls')),
    path('', include('sellerform.urls')),
    path('', include('userprofile.urls')),
    path('inbox/', include('chatting.urls')),
    path('admin/', admin.site.urls),
]

# Add Debug Toolbar URL patterns only for developments

# Serve media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meroherb/sellerform/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views
from core import urls

app_name='sellerform'

urlpatterns=[
        path('seller/',views.sellerform,name='sellerform'),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

meroherb/userprofile/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'userprofile'
urlpatterns =[
    path('userprofile/', views.userprofile, name='userprofile'),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

meroherb/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    seller = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    text = models.TextField(null=True)

meroherb/dashboard/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'w-full py-2 px-4 rounded-xl border focus:outline-none focus:border-blue-500','id':'comment_text'}),
        }

meroherb/dashboard/views.py
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect
from django.contrib.auth import logout
from django.contrib.auth.models import User,Group
from item.models import Item, ItemImageGallery
from .models import Comment
from django.db.models import Avg
from item.models import Item
from userprofile.models import UserProfile




# Create your views here.

    

def dashboardView(request):
    items=Item.objects.all()

    return render(request,'dashboard/dashboard.html',{'items':items})

def logout_view(request):
    logout(request)
    return redirect ("core:login")
def sellerprofile(request, pk):
    seller_info = get_object_or_404(User, pk=pk)
    comments = Comment.objects.filter(seller=seller_info)
    average_rating = comments.aggregate(Avg('rating'))['rating__avg'] or 0
    seller_items=Item.objects.filter(created_by=pk)

    items_with_images = []
    for product in seller_items:
        item_image_gallery = ItemImageGallery.objects.filter(item=product).first()
        product_data = {
            'product': product,
            'image_url': item_image_gallery.images.first().image.url if item_image_gallery and item_image_gallery.images.exists() else None,
        }
        items_with_images.append(product_data)


 
    if request.method == 'POST':
        star_rating = request.POST.get('rating')
        seller_review = request.POST.get('seller_review')
        Comment.objects.create(user=request.user, seller=seller_info, rating=star_rating, text=seller_review)
        return redirect('dashboard:sellerprofile', pk=pk)


    return render(request, 'dashboard/Profile.html', {
        'seller_info': seller_info,
        'comments':comments,
        'avg_rating':average_rating,
        'items_with_images':items_with_images,
    })
    


def home(request):
   
    return dashboardView(request)

def seller_verify(request):
    # group=None
    # seller_status=False
    # if request.user.groups.exists():
    #     group=request.users.groups.all()[0].name
    # print("hello")
    # if group=="seller":
    #     seller_status=True
    # is_seller=False

    # username = request.user.username
    # user = User.objects.get(username=username)
    # user_group=user.groups.all().name

    # seller_group, created = Group.objects.get_or_create(name='seller')

    # for group in user_group:
    #     if group==seller_group:
    #         is_seller=True

    # return render(request,'dashboard/navbar.html',{'is_seller':is_seller})
    username = request.user.username
    user = User.objects.get(username=username)
    is_seller = user.groups.filter(name='seller').exists()

    return render(request, 'dashboard/navbar.html', {'is_seller': is_seller})

meroherb/dashboard/templates/dashboard/Profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>HTML 5 Boilerplate</title>
  <link rel="stylesheet" href="{% static 'Profile.css'%}" />
  <script src="{% static 'Profile.js'%}" defer></script>

  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500;600;800&family=Lobster&display=swap"
    rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
  <div>{% include 'dashboard/navbar.html' %}</div>
  <div class="bg_cover">
    <div class="parent_wrapper">
      <div class="user_parent">
        <div class="user_img">
          <img src="{{ seller_info.selleraccount.image.url }}" />
        </div>

        <div class="user_data">
          <div class="names">
            <div class="f_l_name">{{seller_info.first_name}} {{seller_info.last_name}}</div>
            <div class="user_name">@{{seller_info.username}}</div>
          </div>
          <div class="location">
            <i class="fa-solid fa-location-dot"></i>
            <span class="address">KTM,Nepal</span>
          </div>
          <span class="rating_seller">
            {% if avg_rating %}
            {{avg_rating|floatformat:2}}
            {% for i in "12345" %}
            {% if i|add:"0" <= avg_rating %} <i class="fa fa-star checked" id="check-star"></i>
              {% else %}
              <i class="fa fa-star" id="check-star"></i>
              {% endif %}
              {% endfor %}
              {% else %}
              <!-- If there are no ratings -->
              <i class="fa fa-star" id="star"></i>
              <i class="fa fa-star" id="star"></i>
              <i class="fa fa-star" id="star"></i>
              <i class="fa fa-star" id="star"></i>
              <i class="fa fa-star" id="star"></i>
              &nbsp;<span>No ratings</span>
              {% endif %}
            
            </span>
        </div>
      </div>
    </div>

    <div class="content_parent">
      <div class="navigation_section">
        <div class="products_btn" onclick="showTab('tab1')">Products</div>
        <div class="feedback_btn" onclick="showTab('tab2')">Feedback</div>
      </div>

      <!--content contains products and feedback-->

      <div class="content_body" id="tab1">
        {% for item in items_with_images%}
        <div class="card bg-herb-box rounded-xl mb-6">
          <a href="{% url 'item:detail' item.product.id %}">
              <div class="card-image" style="background-image: url('{{item.image_url}}');position: relative;">
                {% if item.product.discount > 1.00%}
                <p class="showcase-badge">{{item.product.discount}}%</p>
                {%else%}
                {%endif%}
              </div>
        
              <div style="display: flex; flex-flow: column wrap; gap: 1.2vh;">
                  <h2 class="text-xl text-black font-semibold" style="text-decoration: none;">{{ item.product.name }}</h2>
                  <p class="text-gray-500">
                    {% if item.product.discounted_price %}
                    <p style="text-decoration: none; color: hsl(152, 51%, 52%);">${{ item.product.discounted_price|floatformat:2 }}</p>
               
                    {% else %}
                    <p style="color: hsl(152, 51%, 52%);">${{ item.product.price }}</p>
                    {% endif %}
                  </p>
                  <!-- Check for average_rating existence -->
                  {% if item.product.average_rating %}
                      <div class="rating_showcase">
                          <!-- Display stars based on average_rating -->
                          {% for i in "12345" %}
                              {% if i|add:"0" <= item.product.average_rating %}
                                  <i class="fa fa-star checked" id="check-star"></i>
                              {% else %}
                                  <i class="fa fa-star" id="check-star"></i>
                              {% endif %}
                          {% endfor %}
                          <p>Rating: {{ item.product.average_rating|floatformat:2 }}</p>
                      </div>
                      <!-- End of star display -->
                  {% else %}
                      <!-- If there are no ratings -->
                      <div class="rating_showcase">
                          <i class="fa fa-star" id="star"></i>
                          <i class="fa fa-star" id="star"></i>
                          <i class="fa fa-star" id="star"></i>
                          <i class="fa fa-star" id="star"></i>
                          <i class="fa fa-star" id="star"></i>
                          &nbsp;<span>No ratings</span>
                      </div>
                  {% endif %}
              </div>
          </a>
      </div>
      {%endfor%}
    
      </div>


      <div class="content_body" id="tab2">
        <div class="content_feedback">

          <div class="form_parent">


            <p style="font-weight:600;">Write a review</p>
            <form method="Post">
              {% csrf_token %}

              <div class="rating">

                <input type="radio" id="star5" name="rating" value="5" />
                <label class="star" for="star5" title="Awesome" aria-hidden="true"></label>
                <input type="radio" id="star4" name="rating" value="4" />
                <label class="star" for="star4" title="Great" aria-hidden="true"></label>
                <input type="radio" id="star3" name="rating" value="3" />
                <label class="star" for="star3" title="Very good" aria-hidden="true"></label>
                <input type="radio" id="star2" name="rating" value="2" />
                <label class="star" for="star2" title="Good" aria-hidden="true"></label>
                <input type="radio" id="star1" name="rating" value="1" />
                <label class="star" for="star1" title="Bad" aria-hidden="true"></label>

              </div>
              <div class="comment_box">
                <textarea name="seller_review" placeholder="write a review" rows="6" cols="50" id="review-text"
                  required></textarea>
                <input type="submit" class="post_btn" value="Post">

              </div>

            </form>


            {% for x in comments%}
            <div class="comment_body">
              <div class="comment_user">
                <div style="border-radius:50%; height: 50px; width: 50px;">
                  <img src="{% static './dashboard/images/user.png'%}"
                    style="height: 100%; width: 100%; object-fit: cover;">
                </div>
                <div class="user_rat_info">
                  <div class="user_upper">  
                    <h1> @{{x.user}}</h1>
                    <span>{{x.created_at}}</span>
                  </div>
                 
                  <div class="rating_star">

                    {% if x.rating > 0 %}
                    <i class="fa fa-star {% if x.rating  < 1 %} no-checked {% else %} checked {% endif %} "
                      id="check-star"></i>
                    <i class="fa fa-star {% if x.rating  < 2 %} no-checked {% else %} checked {% endif %} "
                      id="check-star"></i>
                    <i class="fa fa-star {% if x.rating  < 3 %} no-checked {% else %} checked {% endif %} "
                      id="check-star"></i>
                    <i class="fa fa-star {% if x.rating  < 4 %} no-checked {% else %} checked {% endif %} "
                      id="check-star"></i>
                    <i class="fa fa-star {% if x.rating  < 5 %} no-checked {% else %} checked {% endif %} "
                      id="check-star"></i>
                    <hr>
                    {% else %}

                    <i class="fa fa-star " id="star"></i>
                    <i class="fa fa-star" id="star"></i>
                    <i class="fa fa-star" id="star"></i>
                    <i class="fa fa-star" id="star"></i>
                    <i class="fa fa-star" id="star"></i>
                    &nbsp;<span>No ratings</span>

                    <hr>

                    {% endif %}

                  </div>


                </div>

              </div>
              <div class="comment">
                <span>{{x.text}}</span>

              </div>



            </div>
            {%endfor%}

          </div>



        </div>
      </div>
    </div>
    <!--end of content-->
  </div>



  <script>
    // Assuming you have an input field with id="comment_text"
    document.getElementById('comment_text').value = ''; // Clears the input field after submission
  </script>
</body>

</html>

meroherb/dashboard/templates/dashboard/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet'>
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500;600;800&family=Lobster&display=swap"
        rel="stylesheet">

 


    <link rel="stylesheet" href="{% static 'footer.css'%}" />
</head>



    <footer class="footer-distributed">
        <div class="footer-left">
            <h3><span>Mero Herbs</span></h3>
            <p class="footer-links">
                <a href="#">Home</a>
                |
                <a href="#">About</a>
                |
                <a href="#">Contact</a>
                |
                <a href="#">Blog</a>
            </p>
        </div>
        <div class="footer-center">
            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>Ghar</span>Nepal</p>
            </div>

            <div>
                <i class="fa fa-phone"></i>
                <p>986126262</p>
            </div>
            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="#">Meroherbs@gmail.com</a></p>
            </div>
        </div>
        <div class="footer-right">
            <p class="footer-company-about">
                <span>About the company</span>
                <strong>MeroHerbs</strong> MeroHerbs is a marketplace for exotic herbs from all over Nepal. We hope you have a nice experience.
        </div>
    </footer>

</html>

meroherb/dashboard/templates/dashboard/imageslider.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0"
    />
    <link rel="stylesheet" href="{% static 'imageslider.css'%}" />
    <script src="{% static "imageslider.js" %}" ></script>
  </head>
  <body>

    <div class="container">
      <div class="slider-wrapper">
        <span class="category-text">Categories</span>
        <span class="category-btn"><a href="{% url 'item:browse'%}">View all categories</a> </span>
        <button id="prev-slide" class="slide-button material-symbols-rounded">
          chevron_left
        </button>
        <ul class="image-list">
          <a href="{% url 'item:category_view' 'culinary' %}">
          <img class="image-item" src="{% static '/dashboard/images/culinary.png'%}" alt="img-1" />
          </a>

          <a href="{% url 'item:category_view' 'essential oils' %}">
          <img class="image-item" src="{% static '/dashboard/images/Group 13951.png'%}" alt="img-1" />
        </a>


          <a href="{% url 'item:category_view' 'herbs spices' %}">
          <img class="image-item" src="{% static '/dashboard/images/herbs.png'%}" alt="img-1" />
        </a>


          <a href="{% url 'item:category_view' 'containers' %}">
          <img class="image-item" src="{% static '/dashboard/images/Group 13952.png'%}" alt="img-1" />
        </a>


          <a href="{% url 'item:category_view' 'aromatherapy' %}">
          <img class="image-item" src="{% static '/dashboard/images/Group 13947.png'%}" alt="img-1" />
        </a>

          <a href="{% url 'item:category_view' 'teas' %}">
          <img class="image-item" src="{% static '/dashboard/images/tea.png'%}" alt="img-1" />
        </a>


          <a href="{% url 'item:category_view' 'health' %}">
          <img class="image-item" src="{% static '/dashboard/images/Group 13948.png'%}" alt="img-1" />
          </a>
        </ul>
        <button id="next-slide" class="slide-button material-symbols-rounded">
          chevron_right
        </button>
      </div>
      <div class="slider-scrollbar">
        <div class="scrollbar-track">
          <div class="scrollbar-thumb"></div>
        </div>
      </div>
    </div>
  </body>
</html>

meroherb/dashboard/templates/dashboard/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet'>
   <link rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0">
   <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500;600;800&family=Lobster&display=swap"
      rel="stylesheet">


   <link rel="stylesheet" href="{% static 'navbar.css'%}" />
   <script src="{% static 'Profile.js'%}" defer></script>

</head>

<body>


   <div class="navbar">
      <div class="logo">
         Mero herbs <span style="color:#FF7426">.</span></div>
      <div class="navbar-links">
         <a href="{% url 'core:main'%}">
            Home
         </a>
         <a href="{% url 'item:browse' %}" class="Browse">
            Browse
         </a>
      </div>

      <div class="user-wrapper">
         {% if request.user.is_authenticated %}
         {% if request.user.selleraccount %}
         {% if request.user.selleraccount.image %}
         <img src="{{ request.user.selleraccount.image.url }}" class="user-icon" onclick="toggleMenu()">
         {% else %}
         <!-- Handle the case where 'image' attribute has no file associated -->
         <img src="{% static '/dashboard/images/user.png' %}" class="user-icon" onclick="toggleMenu()">
         {% endif %}
         {% else %}
         <!-- Handle the case where 'selleraccount' doesn't exist -->
         <img src="{% static '/dashboard/images/user.png' %}" class="user-icon" onclick="toggleMenu()">
         {% endif %}
         {% else %}
         <a href="{% url 'core:login'%}" class="signup">
            <div class="signup-btn"> Login</div>
         </a>
         <a href="{% url 'core:signup'%}" class="signup">
            <div class="signup-btn"> Sign up</div>
         </a>
         {% endif %}
      </div>

      <div class="sub-menu-wrap" id="subMenu">
         <div class="sub-menu" style="border-radius: 20px;">
            <div class="user-info">
               {% if request.user.is_authenticated %}
               {% if request.user.selleraccount %}
               {% if request.user.selleraccount.image %}
                  <img src="{{ request.user.selleraccount.image.url }}" class="user-icon" style="border-radius: 50%;" onclick="toggleMenu()">
               {%endif%}
               {%endif%}

               <h2>{{ request.user.username}}</h2>
               {%else%}
               <img src="{% static '/dashboard/images/user.png'%}" alt="check your connection">
               <h2>Username</h2>
               {%endif%}
            </div>
            <hr>
            <a href="{%url 'userprofile:userprofile' %}" class="sub-menu-link">

               <img src="{% static '/dashboard/images/edit.png'%} " alt=" ">
               <p>Edit profile </p>
               <span>></span>
            </a>

            <a href="{% url 'item:new' %}" class="sub-menu-link">
               <img src="{% static '/dashboard/images/addproduct.png'%} " alt=" ">
               <p>Add product </p>
               <span>></span>
            </a>

            {% if request.user.is_superuser%}
            <a href="{% url 'chatting:inbox' %}" class="sub-menu-link">
               <img src="{% static '/dashboard/images/addproduct.png'%} " alt=" ">
               <p>Inbox </p>
               <span>></span>
            </a>
            {% endif %}

            {% if not request.user.selleraccount%}
            <a href="{% url 'sellerform:sellerform' %}" class="sub-menu-link">
               <img src="{% static '/dashboard/images/seller.png'%} " alt=" ">
               <p>Become Seller </p>
               <span>></span>
            </a>
            {% endif %}

            {% comment %} <a href="#" class="sub-menu-link">

               <img src=" {% static '/dashboard/images/support.png'%}" alt=" ">
               <p>Help and support </p>
               <span>></span>
            </a> {% endcomment %}

            {% if request.user.is_authenticated%}
            <a href="{%url 'dashboard:logout'%}" class="sub-menu-link">

               <img src=" {% static '/dashboard/images/logout.png'%} " alt=" ">
               <p>Logout </p>
               <span>></span>
            </a>
            {% endif %}
         </div>

      </div>