meroherb/chatting/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'chatting'

urlpatterns=[
    path('',views.inbox, name='inbox' ),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

meroherb/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static

app_name='core'

urlpatterns=[
    path('signup/',views.signup,name='signup'),
    path('login/',LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),name="login"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'), name="password_reset"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_sent.html'), name="password_reset_done"), 
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_form.html'), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_done.html'), name="password_reset_complete"), 

    path('main/',views.mainpage,name="main"),


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

meroherb/item/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from .views import GeneratePDF

app_name = 'item'
urlpatterns =[
    path('new/', views.new, name='new'),
    path('browse/',views.browse,name='browse'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('category/<str:pro>',views.Category_view,name="category_view"),
    path('buy_item/<int:pk>/', views.buy_item, name='buy_item'),
    path('generate_pdf/<int:bill_no>/', GeneratePDF.as_view(), name='generate_pdf'),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

meroherb/meroherb/urls.py
# main/urls.py

from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from core.views import mainpage
from django.urls import path, include

# Import Debug Toolbar only for development


app_name = "meroherb"

urlpatterns = [
    path('', include('core.urls')),
    path('',mainpage,name="first"),
    path('', include('dashboard.urls')),
    path('password_reset/', include('django.contrib.auth.urls')),
    path('', include('item.urls')),
    path('', include('sellerform.urls')),
    path('', include('userprofile.urls')),
    path('inbox/', include('chatting.urls')),
    path('admin/', admin.site.urls),
]

# Add Debug Toolbar URL patterns only for developments

# Serve media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meroherb/item/forms.py
from django import forms
from .models import Bill, Item


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name','scientific_name', 'description', 'usage_and_benefits', 'price', 'quantity_available', 'image', )

        widgets = {
            'category': forms.Select(attrs={
                'class': 'category_input'
                
            }),

            'name': forms.TextInput(attrs={
                'class': 'name_input',  # Apply the text-input class from your CSS
                'placeholder':'Name'
            }),

            'scientific_name': forms.TextInput(attrs={
                'class': 'name_input',  # Apply the text-input class from your CSS
                'placeholder':'Scientific name'

            }),

            'description': forms.Textarea(attrs={
                'class': 'description_input',  # Apply the text-input-description class from your CSS
                'placeholder':'Description'

            }),

            'usage_and_benefits': forms.Textarea(attrs={
                'class': 'usage_input',  # Apply the text-input-usage-benefit class from your CSS
                'placeholder':'Usage and benefits'

            }),

            'price': forms.TextInput(attrs={
                'class': 'price_input',  # Apply the text-input-price-field class from your CSS
                'placeholder':'Price'

            }),

            'quantity_available': forms.TextInput(attrs={
                'class': 'quantity_input'  # Apply the text-input-quantity-field class from your CSS
            }),

         
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name','scientific_name', 'description', 'usage_and_benefits', 'price', 'quantity_available', 'image','discount', )

        widgets = {

            'name': forms.TextInput(attrs={
                'class': 'name_input',  # Apply the text-input class from your CSS
                'placeholder':'Name'
            }),

            'scientific_name': forms.TextInput(attrs={
                'class': 'name_input',  # Apply the text-input class from your CSS
                'placeholder':'Scientific name'

            }),

            'description': forms.Textarea(attrs={
                'class': 'description_input',  # Apply the text-input-description class from your CSS
                'placeholder':'Description'

            }),

            'usage_and_benefits': forms.Textarea(attrs={
                'class': 'usage_input',  # Apply the text-input-usage-benefit class from your CSS
                'placeholder':'Usage and benefits'

            }),

            'price': forms.TextInput(attrs={
                'class': 'price_input',  # Apply the text-input-price-field class from your CSS
                'placeholder':'Price'

            }),

            'quantity_available': forms.TextInput(attrs={
                'class': 'quantity_input', # Apply the text-input-quantity-field class from your CSS
                'placeholder':'Quantity in gms'
            }),

            'image': forms.FileInput(attrs={
                'class': 'image_input'
            }),
            'discount': forms.TextInput(attrs={
                'class': 'discount_input',  # Apply the text-input-price-field class from your CSS
                'placeholder':'Discount'

            }),
        }

class BillForm(forms.ModelForm):
    class Meta:
        model = Bill
        fields = ['customer', 'item', 'quantity', 'total_amount']

meroherb/item/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .decorators import allowed_users
from .forms import NewItemForm, EditItemForm, BillForm
from .models import Category, Item, review,ItemImage, Bill
from .models import ItemImageGallery, ItemImage
from django.db import IntegrityError
from decimal import Decimal
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa  
from django.views import View
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.core.files.base import ContentFile
from io import BytesIO

def is_valid_queryparam(param):
    return param != '' and param is not None and param !=0.0   #for price

def browse(request): 
   
    query = request.GET.get('query', '')
    category_id= request.GET.get('category', 0)
    categories=Category.objects.all()
    items = Item.objects.filter(is_sold=False)
    price_min=request.GET.get('input-min',0)
    price_max=request.GET.get('input-max',0)
    for product in items:
            if product.discount > 0:
                print("discount")
                discounted_price = Decimal(product.price) * (1 - Decimal(product.discount) / 100)
                product.discounted_price = discounted_price
                print(discounted_price)
    
    
    items_with_images = []
    for product in items:
        item_image_gallery = ItemImageGallery.objects.filter(item=product).first()
        product_data = {
            'product': product,
            'image_url': item_image_gallery.images.first().image.url if item_image_gallery and item_image_gallery.images.exists() else None,
        }
        items_with_images.append(product_data)
   
    
    if category_id:
        items=items.filter(category_id=category_id)

        for item in items:
            if(item.discount > 0):
                discounted_price = Decimal(product.price) * (1 - Decimal(product.discount) / 100)
                item.discounted_price=discounted_price

       
        items_with_images = []
       

        for product in items:
            item_image_gallery = ItemImageGallery.objects.filter(item=product).first()
            product_data = {
                'product': product,
                'image_url': item_image_gallery.images.first().image.url if item_image_gallery and item_image_gallery.images.exists() else None,
            }
            items_with_images.append(product_data)

    elif query:
        items = items.filter(name__icontains=query)
        items_with_images = []
        for product in items:
            item_image_gallery = ItemImageGallery.objects.filter(item=product).first()
            product_data = {
                'product': product,
                'image_url': item_image_gallery.images.first().image.url if item_image_gallery and item_image_gallery.images.exists() else None,
            }
            items_with_images.append(product_data)

    elif is_valid_queryparam(price_min) and is_valid_queryparam(price_max):
        items = Item.objects.filter(price__range=(float(price_min),float(price_max)))
        items_with_images = []

        for product in items:
            item_image_gallery = ItemImageGallery.objects.filter(item=product).first()
            product_data = {
                'product': product,
                'image_url': item_image_gallery.images.first().image.url if item_image_gallery and item_image_gallery.images.exists() else None,
            }
            items_with_images.append(product_data)

    return render(request,'item/browse.html',{
        'items_with_images': items_with_images,
        'query': query,
        'categories': categories,
        
    })

from django.shortcuts import redirect

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    
    if(item.discount > 0):
                discounted_price = Decimal(item.price) * (1 - Decimal(item.discount) / 100)
                item.discounted_price=discounted_price
                print(discounted_price)
    reviews = review.objects.filter(item=item)
    item_image_gallery = ItemImageGallery.objects.filter(item=item).first()

    if request.method == 'POST':
        star_rating = request.POST.get('rating')
        try:
            review.objects.create(user=request.user, item=item, rating=star_rating)
        except IntegrityError:
            messages.error(request, "Please fill all the fields")
        else:
            # Redirect to the same detail page after successful review submission so that the user should not resubmit data on reload
            return redirect('item:detail', pk=pk)

    return render(request, 'item/detail.html', {
        'item': item,
        'reviews': reviews,
        'item_image_gallery': item_image_gallery,
    })


@login_required
@allowed_users(allowed_roles=['seller'])
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST)
        image_files = request.FILES.getlist("images")

        if form.is_valid():
            if len(image_files) > 3:
                messages.error(request, "You can upload a maximum of 3 images.")
                return render(request, 'item/form.html', {
                'form': form,
                'title': 'New item',}
                )
            
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            # Create an ItemImageGallery instance and associate it with the Item
            item_image_gallery = ItemImageGallery.objects.create(item=item)

            # Add each image to the ItemImageGallery
            for image_file in image_files:
                item_image = ItemImage.objects.create(item=item, image=image_file)
                item_image_gallery.images.add(item_image)

            messages.success(request, "New item created")
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New item',
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk= pk, created_by=request.user)
    item.delete()

    return redirect('item:browse')


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item_image_gallery, created = ItemImageGallery.objects.get_or_create(item=item)

    if request.method == 'POST':
        form = EditItemForm(request.POST, instance=item)
        image_files = request.FILES.getlist("images")

        if form.is_valid():
            if len(image_files) > 3:
                messages.error(request, "You can upload a maximum of 3 images.")
                return render(request, 'item/form.html', {
                'form': form,
                'title': 'New item',}
                )

            form.save()

            # Clear existing images from the gallery
            item_image_gallery.images.clear()

            # Add new images to the gallery
            for image_file in image_files:
                item_image = ItemImage.objects.create(item=item, image=image_file)
                item_image_gallery.images.add(item_image)

            messages.success(request, "Item updated successfully")
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })





def Category_view(request,pro):
    category=Category.objects.get(name=pro)
    products=Item.objects.filter(category=category)

    items_with_images = []
    for product in products:
        item_image_gallery = ItemImageGallery.objects.filter(item=product).first()
        product_data = {
            'product': product,
            'image_url': item_image_gallery.images.first().image.url if item_image_gallery and item_image_gallery.images.exists() else None,
        }
        items_with_images.append(product_data)

    return render(request,'item/browse.html',{'items_with_images':items_with_images,'category':category})


# def buy_item(request, pk):
#     item = get_object_or_404(Item, pk=pk)
    
#     if request.method == 'POST':
#         # Assuming you have a button in your buy_item.html that posts to generate_pdf
#         form = BillForm(request.POST)
#         if form.is_valid():
#             # Create a Bill instance based on the data from Item and the form
#             bill = Bill.objects.create(
#                 customer_name=form.cleaned_data['customer_name'],
#                 item_name=item.name,
#                 quantity=form.cleaned_data['quantity'],
#                 total_amount=form.cleaned_data['total_amount'],
#             )

#             return render(request, 'buy_item.html', {'item': item, 'bill': bill})

#     # Render the buy_item template initially
#     form = BillForm()
#     return render(request, 'buy_item.html', {'form': form, 'item': item})
# def generate_unique_bill_no():
#     timestamp = datetime.now().strftime("%Y%m%d%H%M%S%f")  # Use the current timestamp
#     last_serial_number = Bill.objects.latest('id').id if Bill.objects.exists() else 0
#     serial_number = last_serial_number + 1
#     return f"BILL{serial_number}_{timestamp}"


def buy_item(request, pk):
    item = get_object_or_404(Item, pk=pk)
    discounted_price = 0
    if item.discount > 0:
        discounted_price = Decimal(item.price) * (1 - Decimal(item.discount) / 100)
        item.discounted_price = discounted_price
        print(discounted_price)

    if request.method == 'POST':
        bill = Bill.objects.create(
            customer=request.user,
            item=item,
            quantity=item.quantity_available,
            total_amount=item.price,
            seller=item.created_by.username,
            discount_per=item.discount,

meroherb/item/templates/item/buy_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap"
      rel="stylesheet">

    <link rel="stylesheet" href="{% static 'bill.css'%}"/>
    <title> Item Bill</title>
</head>


<body>

    <div class="root_bill">
        <div class="sub_bill">
          <span class="company_name">Mero herbs</span>

            <div class="bill_no" style="margin-bottom: 1.2vmin;">
                <span style="font-weight: 600; font-size: 1.2rem;">Bill no <span style="text-transform: capitalize; color: blue; "># {{bill.bill_no}} </span> </span>

                {% comment %} <span style="color:#7f868c;">Item name: {{bill.item}} </span> {% endcomment %}
            </div>

            <hr>

            <div class="bill_body">
                <div class="upper_body">
                    <section class="bill_details">
                        <p>
                            <span>Bill from:</span>
                            <span>{{bill.seller}}</span>

                        </p>
                       
                        <p>
                            <span>Bill to:</span>
                            <span>{{bill.customer}}</span>
                        </p>

                        <p>
                            <span>Issued on:</span>
                            <span>{{bill.issued_date_time}}</span>
                        </p>

                        <p>
                            <span>Payment method:</span>
                            <span>Cash on delivery</span>
                        </p>

                        <p>
                            <span>Delivery Location:</span>
                            <span>{{bill.delivery}}</span>
                        </p>

                        <p>
                            <span>Buyer Contact Number:</span>
                            <span>{{bill.contact_info}}</span>
                        </p>

                    </section>
                </div>

                <div class="lower_body">
                    <span style="font-size: 0.875rem;">Invoice details</span>
                    <section class="bill_section">
                        <hr>
                        <div class="bill_heading" style="color: #7f868c;">
                            <span> Description</span>
                            <span>Price</span>
                            <span>Discount</span>
                            <span>Qty</span>
                            <span>Total amount after discount</span>
                        </div>
                        <hr>

                        <div class="bill_content">
                            <span>{{bill.item}}</span>
                            <span style="color: #008148;">${{bill.total_amount}}</span>
                            <span>{{bill.discount_per}}%</span>
                            <span>{{bill.quantity}}</span>
                            <!-- <span style="color: #008148;">${{bill.discount_price}}</span> -->
                            {% if bill.discount_price > 0 %}
                                <!-- <del>${{ item.price }}</del> -->
                                <span style="color: #008148;">${{bill.discount_price}} </span>
                            {% else %}
                                <span style="color: #008148;">${{bill.total_amount}} </span>
                            {% endif %}
                        </div>

                        <hr>
                        {% comment %} <div class="total_amt">
                            <span>Grand total</span>
                            <span style="color: #008148;"> Rs 28282828</span>
                        </div> {% endcomment %}
                    </section>


                </div>
            </div>

            <div class="button_section">

            </div>

        </div>
        <form id="generatePdfForm" method="post" action="{% url 'item:generate_pdf' bill.bill_no %}">
          {% csrf_token %}
          <input type="hidden" name="customer_name" value="{{ bill.customer }}">
          <input type="hidden" name="item_name" value="{{ bill.item }}">
          <input type="hidden" name="quantity" value="{{ bill.quantity }}">
          <input type="hidden" name="total_amount" value="{{ bill.total_amount }}">
          <button type="submit" id="generatePdfBtn">Generate PDF</button>
        </form>
       

    </div>
    

   

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>


{% comment %} <script>
    document.getElementById('generatePdfBtn').addEventListener('click', function () {
        // Submit the form using JavaScript
        document.getElementById('generatePdfForm').submit();
    });
</script> {% endcomment %}

meroherb/item/templates/item/detail.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ item.name }}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'detail.css'%}">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500;600;800&family=Lobster&display=swap">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</head>

<header>
    {% include 'dashboard/navbar.html'%}
</header>

<body>
    {% for msg in messages%}
    <div class="alert alert-warning"  role="alert">
      {{msg}}
  </div>
    {%endfor%}
    <div class="main-container">


    <div class="image_section">
        <div class="main_image">
            <a href="#" class="clickable-image" data-main-image="{{ item_image_gallery.images.first.image.url }}">
                <img src="{{ item_image_gallery.images.first.image.url }}">
            </a>
        </div>
        <div class="sub_image">
            {% for image in item_image_gallery.images.all|slice:"0:" %}
                <div class="other_image">
                    <a href="#" class="clickable-image" data-main-image="{{ image.image.url }}">
                        <img src="{{ image.image.url }}" alt="Other Image">
                    </a>
                </div>
            {% endfor %}
        </div>
    
    

        <div class="product_details_main">
            <div class="product_upper">
                <div class="product_detail">
                    <span class="product_name"> {{item.name}}</span>

                    <div class="category_section">
                        <span class="category_text">Category:</span>
                        <strong>{{item.category}} </strong>
                    </div>
                </div>
                <div class="product_detail_mid">
                    <div class="product_quantity">
                        <span style="color:#545454;"> QUANTITY</span>
                        <strong>{{item.quantity_available}}</strong>
                    </div>
                    <div class="product_price">
                        <span style="color: #545454;">PRICE</span>
                        <section style="font-size: 1rem; color: #008148;">
                            {% if item.discounted_price %}
                            <p class="price"><strong>${{ item.discounted_price|floatformat:2 }}</strong></p>
                            {% if item.discount > 0 %}
                                <del>${{ item.price }}</del>
                                <span style="font-size: 0.91rem;">({{item.discount}}% off) </span>

                            {% endif %}
                            {% else %}
                            <p class="price"><strong>${{ item.price }}</strong></p>
                            {% endif %}

                        </section>
                    </div>
                </div>

                {% if request.user == item.created_by %}
                <div class="product_edit_section">
                    <a href="{% url 'item:edit' item.id %}">
                        <div class="edit_btn">Edit </div>

                    </a>
                    <a href="{% url 'item:delete' item.id %}">
                        <div class="delete_btn"> Delete </div>
                    </a>

                </div>
                {% else %}
                <div class="product_buy_section">
                    {% comment %} <p>Item ID: {{ item.id }}</p> {% endcomment %}
                
                    <form method="post" action="{% url 'item:buy_item' item.id %}">
                        {% csrf_token %}
                        <button type="submit" class="buy_btn">Buy</button>
                    </form>
                </div>
                
                {%endif%}

                {% comment %} {% else %}
                <div class="product_buy_section">
                    <a href="{% url 'chatting:new' item.id %}">
                        <div class="buy_btn">
                            Buy
                        </div>
                    </a>
                </div>
                {%endif%} {% endcomment %}



            </div>

            <div class="product_lower">

                <div class="window_navigation">
                    <span class="nav_btn">Description</span>
                    <span class="nav_btn">Usage and Benefits</span>
                    <span class="nav_btn">Seller info</span>
                    <span class="nav_btn">Review</span>
                </div>

                <div class="content_box">

                    <div class="window_content">
                        {{item.description}}
    
                    </div>


                    <div class="window_content">

                        {{item.usage_and_benefits}}
                        
                    </div>
                    <div class="window_content">
    
                        {{item.created_by.username}}
                        
                    </div>

                    <div class="window_content" id="rating_window">
                        {% include 'item/rating.html'%}
                    </div>

                </div>

                
                

            </div>

        </div>

        
    </div>
</div>


    <script>
        const tabs_btn=document.querySelectorAll('.nav_btn');
        const body_content= document.querySelectorAll('.window_content');

        tabs_btn.forEach((btn,index)=>{
            btn.addEventListener('click',()=>{
                tabs_btn.forEach(btn=>{btn.classList.remove('active')})
                btn.classList.add('active');

                body_content.forEach(content=>{content.classList.remove('active')})
                body_content[index].classList.add('active');

            })
        })

    </script>
    <script src="{% static 'detail.js' %}"></script>


</body>

    {% include 'dashboard/footer.html'%}


</html>